version: '3.8'
services:
  app:
    build: .
    ports:
      - "3001:3001"
    volumes:
      - .:/usr/src/app
    command: ["pm2-runtime", "start", "npm", "--name","admin","--","run","dev","--","-p","3001"]